### PR TITLE
initial fastlane structures from IzzyOnDroid

### PR DESCRIPTION
**Pull request by IzzySoft**
As discussed in #47 this is the package with Fastlane structures from my repo. Be welcome to build on it, e.g. adding a featureGraphic, expanding the description etc. For guidance, some hints:

* my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for what goes where and what the limits are (like, short description max 80 chars, icon 48x48 to max 512x512 px etc)
* [my Wiki on Fastlane formattings](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for the `full_description.txt` (I'm using HTML here condensed to a single line, as that what looks best with my repo *and* F-Droid.org – my updater takes care for "condensing", but F-Droid's does not. Some hints are behind the link
* as a general hint which you might not need: [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss) :wink:

Enjoy!

### CODE REVIEW

**Comment by IzzySoft** [comment]
Cool! Please let me know when they are merged (and thus reached their "final destination"), so I can enable it on my end to have the structures checked for changes whenever pulling a new release. Thanks!

**Comment by AdamGuidarini** [comment]
Can do! Thanks for your help!

**Comment by AdamGuidarini** [comment]
Hello I just create a release for version 0.11.0

**Comment by IzzySoft** [comment]
Cool, thanks! Config updated to include the fastlane check. Aaaand:

```
$ iod repo get projects.medicationtracker
projects.medicationtracker: looking for 'https://api.github.com/repos/AdamGuidarini/MediTrak/releases'
projects.medicationtracker: checking tag 'v0.11.0'
projects.medicationtracker: lastRelNo set to '0.11.0', checking for files
projects.medicationtracker: Upstream file date (2023-12-20 19:56) is newer than ours (2023-12-17 19:01).
projects.medicationtracker: returning ['0.11.0','https://github.com/AdamGuidarini/MediTrak/releases/download/v0.11.0/meditrak_0_11_0.apk',1703098595]
projects.medicationtracker: 0.10.0/0.11.0, https://github.com/AdamGuidarini/MediTrak/releases: https://github.com/AdamGuidarini/MediTrak/releases/download/v0.11.0/meditrak_0_11_0.apk
- Grabbing update for projects.medicationtracker: OK
- Checking 'repo/projects.medicationtracker_11.apk' for libraries and malware …
projects.medicationtracker: check if repo contains FUNDING.yml
projects.medicationtracker: looking for 'https://api.github.com/repos/AdamGuidarini/MediTrak/contents/.github'
projects.medicationtracker: Github reports "Not Found" for https://api.github.com/repos/AdamGuidarini/MediTrak/contents/.github
projects.medicationtracker: looking for 'https://api.github.com/repos/AdamGuidarini/MediTrak/contents/'
projects.medicationtracker: no FUNDING.yml detected.
projects.medicationtracker: calling 'getFastlaneMeta(github,[host:github.com,owner:AdamGuidarini,repo:MediTrak,path:/fastlane/metadata/android])'
projects.medicationtracker: FastlaneFeatures shortdesc,fulldesc,icon,screenshots
projects.medicationtracker: looking for 'https://api.github.com/repos/AdamGuidarini/MediTrak/contents/fastlane%2Fmetadata%2Fandroid'
projects.medicationtracker: looking for 'https://api.github.com/repos/AdamGuidarini/MediTrak/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US'
projects.medicationtracker: looking for 'https://api.github.com/repos/AdamGuidarini/MediTrak/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages'
projects.medicationtracker: looking for 'https://api.github.com/repos/AdamGuidarini/MediTrak/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages%2FphoneScreenshots'
projects.medicationtracker: checking locale 'en-US'
projects.medicationtracker: updating 'metadata/projects.medicationtracker/en-US/full_description.txt'
projects.medicationtracker: updating 'metadata/projects.medicationtracker/en-US/short_description.txt'
projects.medicationtracker: updating 'repo/projects.medicationtracker/en-US/icon.png'
projects.medicationtracker: updating 'repo/projects.medicationtracker/en-US/phoneScreenshots/01.png'
projects.medicationtracker: updating 'repo/projects.medicationtracker/en-US/phoneScreenshots/02.png'
projects.medicationtracker: updating 'repo/projects.medicationtracker/en-US/phoneScreenshots/03.png'
projects.medicationtracker: updating 'repo/projects.medicationtracker/en-US/phoneScreenshots/04.png'
projects.medicationtracker: cross-checking for obsolete screenshots
projects.medicationtracker: screenshots in Fastlane: 01,02,03,04
projects.medicationtracker: local screenshots checked: 01,02,03,04
```

Looks good!

**Comment by AdamGuidarini** [comment]
Perfect!

**Pull request merged**
